---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    yum: name=git state=present
  - name: clone the repo from github
    git: repo=https://github.com/Blessing-123/projCert.git dest=/tmp/gitrepo
  - name: Running the container
          docker_container:
            image: devopsedu/webapp
            path: docker
            state: running
            
        - name: Check if container is running
          shell: docker ps
